#define IP_VERSION_V4 4
#define IP_VERSION_V6 6
#define IP_DEFAULT_IHL 5
#define IP_DEFAULT_FRAGMENT_OFFSET	0
#define IP_DEFAULT_IDENTIFICATION 	0
#define IP_DEFAULT_TTL 64
#define IP_TCP_PROTOCOL 6
#define IP_UDP_PROTOCOL 17
#define IP_ICMP_PROTOCOL 1
#define IP_IGMP_PROTOCOL 2
#define IP_DEFAULT_LENGTH 60
#define TCP_DEFAULT_OFFSET 5
#define TCP_DEFAULT_WINDOW 65535
#define TCP_DEFAULT_RESERVED 0
#define TCP_DEFAULT_URG_POINTER 0
#define TCP_DEFAULT_TCP_OPTIONS 0
#define ICMP_TYPE_UNREACHABLE 3
#define ICMP_TYPE_ROUTER_ADVERTISEMENT 9
#define ICMP_CODE_NET_UNREACHABLE 0
#define ICMP_CODE_HOST_UNREACHABLE 1
#define ICMP_CODE_PROTOCOL_UNREACHABLE 2
#define ICMP_CODE_PORT_UNREACHABLE 3
#define ICMP_CODE_FRAMENTATION_NEEDED 4
#define ICMP_CODE_SOURCE_ROUTE_FAILED 5

// Precedence critical,low delay,high throughput and normal reliability
#define IP_CRITIC_TOS 0b1011101
// Precedence Routine,normal delay, normal throughput and normal reliability
#define IP_CURRENT_TOS 0x00
